### ISSUE TITLE
CUDA is oom

### ISSUE THREAD

**Issue by antimattergroup** [DiffusionLight/DiffusionLight#21]
with run python inpaint.py --dataset <input_directory> --output_dir <output_directory>
I got this error..

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 79.33 GiB total capacity; 7.10 GiB already allocated; 2.44 MiB free; 7.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by pureexe** [comment]
80Gb VRAM and still OOM 😱.

We are testing on 16GB VRAM and it works fine.

However, Can you run the example image that we provide in example folder?

If yes, it's the problem about input file
If no, it's a problem about environment setup

**Comment by antimattergroup** [comment]
> 80Gb VRAM 但仍然 OOM 😱。
> 
> 我们正在 16GB VRAM 上进行测试，效果良好。
> 
> 但是，您可以运行我们在示例文件夹中提供的示例图像吗？
> 
> 如果是，则是输入文件的问题 如果不是，则是环境设置的问题

Yea.. I am shocked too.
I running via the default bed.png and got this error, all settings are default, such confused..
another point is my VRAM is more large than yours, why could I got this.XD

**Comment by pureexe** [comment]
Let's make sure that you didn't have any other process that already running on the same GPU.

Also, you may try the simple version of DiffusionLight to see if can run.

See the chromeball generation section in HuggingFace page for a simple version:

https://huggingface.co/DiffusionLight/DiffusionLight#chromeball-generation

**Comment by antimattergroup** [comment]
> 让我们确保没有任何其他进程已在同一 GPU 上运行。
> 
> 另外，您可以尝试一下DiffusionLight的简单版本，看看是否可以运行。
> 
> 请参阅 HuggingFace 页面中的 chromeball 生成部分，了解普通的现成代码：
> 
> [https://huggingface.co/DiffusionLight/DiffusionLight#chromeball- Generation](https://huggingface.co/DiffusionLight/DiffusionLight#chromeball-generation)

I'm sorry I am new as on remote dev.
my leader told me I was running my code on a full memory card.
so it's clear now, my fault, lmao..

**Comment by pureexe** [comment]
DiffusionLight code (this repo) need 13GB VRAM to run. So, it can't fit on 3070.

You may tried ComfyUI version instead. ComfyUI has better optimization than our code. It might be able to run on 8gb

https://github.com/kijai/ComfyUI-DiffusionLight
